export const programs = [
  'Datadriven utveckling',
  'Datateknik',
  'Design och produktutveckling',
  'Elektronik och systemdesign',
  'Elektronikdesign',
  'Energi - miljö - management',
  'Industriell ekonomi',
  'Industriell ekonomi - internationell',
  'Informationsteknologi',
  'Kemisk biologi',
  'Kommunikation, transport och samhälle',
  'Maskinteknik',
  'Medieteknik',
  'Medieteknik och AI',
  'Medicinsk teknik',
  'Mjukvaruteknik',
  'Teknisk biologi',
  'Teknisk fysik och elektroteknik',
  'Teknisk fysik och elektroteknik - internationell',
  'Teknisk matematik',
];
