// accordionItemsConfig.ts
import { AccordionItemProps } from './types';
import {
  BetweenHorizontalStart,
  AlignVerticalJustifyCenter,
  Blocks,
  Gauge,
  Network,
  SignpostBig,
  NotebookPen,
  School,
} from 'lucide-react';

export const accordionItems: AccordionItemProps[] = [
  {
    value: 'semester',
    title: 'Termin',
    filterType: 'semester',
    options: ['7', '8', '9'],
    displayValue: (semester) => `Termin ${semester}`,
    icon: BetweenHorizontalStart,
  },
  {
    value: 'period',
    title: 'Period',
    filterType: 'period',
    options: ['1', '2'],
    displayValue: (period) => `Period ${period}`,
    icon: AlignVerticalJustifyCenter,
  },
  {
    value: 'block',
    title: 'Block',
    filterType: 'block',
    options: ['1', '2', '3', '4'],
    displayValue: (block) => `Block ${block}`,
    icon: Blocks,
  },
  {
    value: 'studyPace',
    title: 'Studietakt',
    filterType: 'studyPace',
    options: ['Helfart', 'Halvfart'],
    displayValue: (pace) => pace.toString(),
    icon: Gauge,
  },
  {
    value: 'level',
    title: 'Utbildningsnivå',
    filterType: 'courseLevel',
    options: ['Grundnivå', 'Avancerad nivå'],
    displayValue: (level) => level.toString(),
    icon: Network,
  },
  {
    value: 'fieldOfStudy',
    title: 'Huvudområde',
    filterType: 'mainFieldOfStudy',
    options: [
      'Biologi',
      'Bioteknik',
      'Datateknik',
      'Datavetenskap',
      'Design',
      'Elektroteknik',
      'Energi- och miljöteknik',
      'Flygteknik',
      'Fysik',
      'Grafisk design och kommunikation',
      'Industriell ekonomi',
      'Informationsteknologi',
      'Kemi',
      'Kemisk biologi',
      'Kemiteknik',
      'Logistik',
      'Maskinteknik',
      'Matematik',
      'Medicinsk teknik',
      'Medieteknik',
      'Produktutveckling',
      'Programmering',
      'Teknisk biologi',
      'Teknisk fysik',
      'Tillämpad matematik',
      'Transportsystem',
      'Inget huvudområde',
    ],
    displayValue: (field) => field.toString(),
    icon: SignpostBig,
  },
  {
    value: 'examinations',
    title: 'Examination',
    filterType: 'examinations',
    options: ['Tentamen', 'Laborationer', 'Projekt', 'Inlämning'],
    displayValue: (type) => type.toString(),
    icon: NotebookPen,
  },
  {
    value: 'campus',
    title: 'Campus',
    filterType: 'campus',
    options: ['Norrköping', 'Linköping'],
    displayValue: (campus) => campus.toString(),
    icon: School,
  },
];
